/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package CiscoGT.Interfaces;

import CiscoGT.ConfigCHAT.ChatInterfaz;
import CiscoGT.ConfigCHAT.Mensaje;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.net.URL;
import java.rmi.RemoteException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextPane;
import static javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER;

/**
 *
 * @author Carlos Bautista
 * @CanalOficcial Cisco GT
 * @Carrera Ingenieria en Sistemas y TICs
 * 
 */

public class VerChat extends javax.swing.JFrame implements MouseListener, KeyListener
{   
    String username;
    ChatInterfaz chat;
    List<Mensaje> msgs = new ArrayList<>();
    List<String> users = new ArrayList<>();

    /** Creates new form VerChat */
    public VerChat(ChatInterfaz chat, String username) throws RemoteException 
    {
        initComponents();
        this.chat = chat;
        this.username = username;
        chat.login(username);
        execute();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userListTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        boton1 = new CiscoGT.Interfaces.Boton();
        boton2 = new CiscoGT.Interfaces.Boton();
        boton3 = new CiscoGT.Interfaces.Boton();
        boton4 = new CiscoGT.Interfaces.Boton();
        jPanel3 = new javax.swing.JPanel();
        logoutButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        chatListTextArea = new javax.swing.JTextPane();
        chatInputText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        LentesLabel = new javax.swing.JLabel();
        dudaLabel = new javax.swing.JLabel();
        desacuerdoLabel = new javax.swing.JLabel();
        llorandoLabel = new javax.swing.JLabel();
        provacandoLabel = new javax.swing.JLabel();
        carcajadasLabel = new javax.swing.JLabel();
        coraojosLabel = new javax.swing.JLabel();
        besitosLabel = new javax.swing.JLabel();
        tapabocaLabel = new javax.swing.JLabel();
        fiebreLabel = new javax.swing.JLabel();
        gatoriendoLabel = new javax.swing.JLabel();
        gatocoraLabel = new javax.swing.JLabel();
        abueloLabel = new javax.swing.JLabel();
        angelLabel = new javax.swing.JLabel();
        pandaLabel = new javax.swing.JLabel();
        okLabel = new javax.swing.JLabel();
        monoojosLabel = new javax.swing.JLabel();
        monoorejasLabel = new javax.swing.JLabel();
        monobocaLabel = new javax.swing.JLabel();
        abuelaLabel = new javax.swing.JLabel();
        nolikeLabel = new javax.swing.JLabel();
        likeLabel = new javax.swing.JLabel();
        bicepLabel = new javax.swing.JLabel();
        cruzLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 1, true));

        userListTextArea.setEditable(false);
        userListTextArea.setBackground(new java.awt.Color(0, 153, 204));
        userListTextArea.setColumns(20);
        userListTextArea.setRows(5);
        jScrollPane1.setViewportView(userListTextArea);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Redes sociales");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Usuarios en línea");

        boton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/YT.png"))); // NOI18N
        boton1.setLink("https://www.youtube.com/c/CiscoGT");

        boton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ITG.png"))); // NOI18N
        boton2.setLink("https://www.instagram.com/3l_1ng3/");

        boton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TW.png"))); // NOI18N
        boton3.setLink("https://twitter.com/cisco_502");

        boton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FB.png"))); // NOI18N
        boton4.setLink("https://www.facebook.com/InternationalNewsIT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(boton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(boton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(boton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(boton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 250, 480));

        jPanel3.setBackground(new java.awt.Color(0, 153, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        jPanel3.setForeground(new java.awt.Color(0, 153, 204));

        logoutButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 0, 0));
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel3.setBackground(new java.awt.Color(255, 0, 0));
        jLabel3.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Usuario:");

        chatListTextArea.setEditable(false);
        chatListTextArea.setContentType("text/html"); // NOI18N
        chatListTextArea.setForeground(new java.awt.Color(255, 255, 255));
        chatListTextArea.setSelectionColor(new java.awt.Color(204, 204, 255));
        chatListTextArea.setSelectionEnd(6);
        chatListTextArea.setSelectionStart(6);
        jScrollPane2.setViewportView(chatListTextArea);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/enviar1.png"))); // NOI18N
        jButton1.setText("Enviar");
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/enviar1.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/enviar2.png"))); // NOI18N
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(logoutButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(chatInputText, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(logoutButton))
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chatInputText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(21, 21, 21))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 370, 480));

        jPanel4.setBackground(new java.awt.Color(0, 153, 204));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Emojis: ");

        LentesLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/0.png"))); // NOI18N
        LentesLabel.setToolTipText("");
        LentesLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        dudaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1.png"))); // NOI18N
        dudaLabel.setToolTipText("");
        dudaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        desacuerdoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2.png"))); // NOI18N
        desacuerdoLabel.setToolTipText("");
        desacuerdoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        llorandoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/3.png"))); // NOI18N
        llorandoLabel.setToolTipText("");
        llorandoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        provacandoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4.png"))); // NOI18N
        provacandoLabel.setToolTipText("");
        provacandoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        carcajadasLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/5.png"))); // NOI18N
        carcajadasLabel.setToolTipText("");
        carcajadasLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        coraojosLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/6.png"))); // NOI18N
        coraojosLabel.setToolTipText("");
        coraojosLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        besitosLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/7.png"))); // NOI18N
        besitosLabel.setToolTipText("");
        besitosLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tapabocaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/8.png"))); // NOI18N
        tapabocaLabel.setToolTipText("");
        tapabocaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        fiebreLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/9.png"))); // NOI18N
        fiebreLabel.setToolTipText("");
        fiebreLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        gatoriendoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/10.png"))); // NOI18N
        gatoriendoLabel.setToolTipText("");
        gatoriendoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        gatocoraLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/11.png"))); // NOI18N
        gatocoraLabel.setToolTipText("");
        gatocoraLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        abueloLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/16.png"))); // NOI18N
        abueloLabel.setToolTipText("");
        abueloLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        angelLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/17.png"))); // NOI18N
        angelLabel.setToolTipText("");
        angelLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pandaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/18.png"))); // NOI18N
        pandaLabel.setToolTipText("");
        pandaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        okLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/19.png"))); // NOI18N
        okLabel.setToolTipText("");
        okLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        monoojosLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/12.png"))); // NOI18N
        monoojosLabel.setToolTipText("");
        monoojosLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        monoorejasLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/13.png"))); // NOI18N
        monoorejasLabel.setToolTipText("");
        monoorejasLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        monobocaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/14.png"))); // NOI18N
        monobocaLabel.setToolTipText("");
        monobocaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        abuelaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/15.png"))); // NOI18N
        abuelaLabel.setToolTipText("");
        abuelaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        nolikeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/20.png"))); // NOI18N
        nolikeLabel.setToolTipText("");
        nolikeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        likeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/21.png"))); // NOI18N
        likeLabel.setToolTipText("");
        likeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        bicepLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/22.png"))); // NOI18N
        bicepLabel.setToolTipText("");
        bicepLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cruzLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/23.png"))); // NOI18N
        cruzLabel.setToolTipText("");
        cruzLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(LentesLabel)
                        .addGap(18, 18, 18)
                        .addComponent(dudaLabel)
                        .addGap(18, 18, 18)
                        .addComponent(desacuerdoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(llorandoLabel))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(provacandoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(carcajadasLabel)
                        .addGap(18, 18, 18)
                        .addComponent(coraojosLabel)
                        .addGap(18, 18, 18)
                        .addComponent(besitosLabel))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(tapabocaLabel)
                        .addGap(18, 18, 18)
                        .addComponent(fiebreLabel)
                        .addGap(18, 18, 18)
                        .addComponent(gatoriendoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(gatocoraLabel))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(monoojosLabel)
                        .addGap(18, 18, 18)
                        .addComponent(monoorejasLabel)
                        .addGap(18, 18, 18)
                        .addComponent(monobocaLabel)
                        .addGap(18, 18, 18)
                        .addComponent(abuelaLabel))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(abueloLabel)
                        .addGap(18, 18, 18)
                        .addComponent(angelLabel)
                        .addGap(18, 18, 18)
                        .addComponent(pandaLabel)
                        .addGap(18, 18, 18)
                        .addComponent(okLabel))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(nolikeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(likeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(bicepLabel)
                        .addGap(18, 18, 18)
                        .addComponent(cruzLabel)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LentesLabel)
                    .addComponent(dudaLabel)
                    .addComponent(desacuerdoLabel)
                    .addComponent(llorandoLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(provacandoLabel)
                    .addComponent(carcajadasLabel)
                    .addComponent(coraojosLabel)
                    .addComponent(besitosLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tapabocaLabel)
                    .addComponent(fiebreLabel)
                    .addComponent(gatoriendoLabel)
                    .addComponent(gatocoraLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(monoojosLabel)
                    .addComponent(monoorejasLabel)
                    .addComponent(monobocaLabel)
                    .addComponent(abuelaLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(abueloLabel)
                    .addComponent(angelLabel)
                    .addComponent(pandaLabel)
                    .addComponent(okLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nolikeLabel)
                    .addComponent(likeLabel)
                    .addComponent(bicepLabel)
                    .addComponent(cruzLabel))
                .addGap(0, 26, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 270, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        try 
        {
            chat.logout(username);  // usa la referencia "chat" para llamar a métodos remotos
            System.exit(0);
            // se pueden producir las excepciones, URL de basura, RemoteException
        } 
        catch (RemoteException ex) 
        {
            Logger.getLogger(VerChat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        sendNewMessage();
    }//GEN-LAST:event_jButton1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LentesLabel;
    private javax.swing.JLabel abuelaLabel;
    private javax.swing.JLabel abueloLabel;
    private javax.swing.JLabel angelLabel;
    private javax.swing.JLabel besitosLabel;
    private javax.swing.JLabel bicepLabel;
    private CiscoGT.Interfaces.Boton boton1;
    private CiscoGT.Interfaces.Boton boton2;
    private CiscoGT.Interfaces.Boton boton3;
    private CiscoGT.Interfaces.Boton boton4;
    private javax.swing.JLabel carcajadasLabel;
    private javax.swing.JTextField chatInputText;
    private javax.swing.JTextPane chatListTextArea;
    private javax.swing.JLabel coraojosLabel;
    private javax.swing.JLabel cruzLabel;
    private javax.swing.JLabel desacuerdoLabel;
    private javax.swing.JLabel dudaLabel;
    private javax.swing.JLabel fiebreLabel;
    private javax.swing.JLabel gatocoraLabel;
    private javax.swing.JLabel gatoriendoLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel likeLabel;
    private javax.swing.JLabel llorandoLabel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel monobocaLabel;
    private javax.swing.JLabel monoojosLabel;
    private javax.swing.JLabel monoorejasLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nolikeLabel;
    private javax.swing.JLabel okLabel;
    private javax.swing.JLabel pandaLabel;
    private javax.swing.JLabel provacandoLabel;
    private javax.swing.JLabel tapabocaLabel;
    private javax.swing.JTextArea userListTextArea;
    // End of variables declaration//GEN-END:variables
    
    private void execute() 
    {
        userListTextArea.setLineWrap(true);     // para eliminar la barra de desplazamiento horizontal
        setTitle("Q-Chat");  
        setImages();
        addListeners();      
        this.nameLabel.setText(username);
        this.setVisible(true);
        setLocationRelativeTo(null);            // para ver la GUI en el medio de la pantalla
        Thread t1 = new Thread(new Runnable() 
        {
            @Override
            public void run() 
            {
                while (true) 
                {
                    refresh();                  // este hilo se usa para actualizar la ventana de chat cada segundo 
                    try                         // para mostrar toda la lista de chat
                    {                       
                        Thread.sleep(1000);
                    } 
                    catch (InterruptedException ex) 
                    {
                        Logger.getLogger(VerChat.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });
        t1.start();
    }
    
    public void displayChatList() throws RemoteException 
    {
        chatListTextArea.setText("");
        msgs = chat.getAllMessages();
        String doc = "<html><body><table>";
        for (Mensaje m : msgs) 
        {
            if (!((m.getUsuario().equals(username)) && (m.getTipo().equals("unirse")))) 
            {             
                String smileyName = m.getSmil();               
                Date date = m.getDatos();
                DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
                String a = dateFormat.format(date);
                SimpleDateFormat parseFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
                SimpleDateFormat printFormat = new SimpleDateFormat("HH:mm:ss");
                try 
                {
                    Date time = parseFormat.parse(a);
                    if (smileyName == null) 
                    {
                        doc += "<tr><td>" 
                                + printFormat.format(time) 
                                + "</td><td><font color='rgb(55,178,204)'><b>" 
                                + m.getUsuario() 
                                + "</b></font></td><td> " 
                                + m.getMsg() 
                                + "</td></tr>";
                    } 
                    else 
                    {                  
                        doc += "<tr><td>" 
                                + printFormat.format(time) 
                                + "</td><td><font color='rgb(55,178,204)'><b>" 
                                + m.getUsuario()  
                                + "</b></font></td><td><img src= '" 
                                + this.getClass().getResource("/Imagenes/"+smileyName) 
                                + "' width=50 height=50 /> </td></tr>";
                    }
                } 
                catch (ParseException ex) 
                {
                    Logger.getLogger(VerChat.class.getName()).log(Level.SEVERE, null, ex);
                }                        
            }
        }
        doc += "</table></body></html>";
        chatListTextArea.setText(doc);
    }

    private void displayUserList() throws RemoteException 
    {
        userListTextArea.setText("");
        users = chat.getAllUsers();
        for (String u : users) 
        {
            if (!u.equals(username)) 
            {             
                userListTextArea.append(" " + u + "\n");             
            }
        }
    }
    
    public void refresh() 
    {
        try 
        {
            displayChatList();
            displayUserList();
        } 
        catch (RemoteException ex) 
        {
            Logger.getLogger(VerChat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setImages() 
    {
        ImageIcon icons[] = new ImageIcon[24];
        for (int i = 0; i < 24; i++) 
        {
            icons[i] = new ImageIcon(getClass().getResource("/Imagenes/" + i + ".png"));
        }
        LentesLabel.setIcon(icons[0]);
        dudaLabel.setIcon(icons[1]);
        desacuerdoLabel.setIcon(icons[2]);
        llorandoLabel.setIcon(icons[3]);
        provacandoLabel.setIcon(icons[4]);
        carcajadasLabel.setIcon(icons[5]);
        coraojosLabel.setIcon(icons[6]);
        besitosLabel.setIcon(icons[7]);
        tapabocaLabel.setIcon(icons[8]);
        fiebreLabel.setIcon(icons[9]);
        gatoriendoLabel.setIcon(icons[10]);
        gatocoraLabel.setIcon(icons[11]);
        monoojosLabel.setIcon(icons[12]);
        monoorejasLabel.setIcon(icons[13]);
        monobocaLabel.setIcon(icons[14]);
        abuelaLabel.setIcon(icons[15]);
        abueloLabel.setIcon(icons[16]);
        angelLabel.setIcon(icons[17]);
        pandaLabel.setIcon(icons[18]);
        okLabel.setIcon(icons[19]);
        nolikeLabel.setIcon(icons[20]);
        likeLabel.setIcon(icons[21]);
        bicepLabel.setIcon(icons[22]);
        cruzLabel.setIcon(icons[23]);
    }
    
    
    @Override
    public void mouseClicked(MouseEvent e) 
    {
        Mensaje message = new Mensaje();
        message.setUsuario(username);
        message.setTipo("client");
        message.setDatos(new Date());
        
        if (e.getSource() == LentesLabel) 
        {
            message.setSmil("0.png");
        } 
        else 
            if (e.getSource() == dudaLabel) 
        {
            message.setSmil("1.png");
        } 
        else 
            if (e.getSource() == desacuerdoLabel) 
        {
            message.setSmil("2.png");
        } else 
                if (e.getSource() == llorandoLabel) 
        {
            message.setSmil("3.png");
        } else 
                    if (e.getSource() == provacandoLabel) 
        {
            message.setSmil("4.png");
        } else 
                    if (e.getSource() == carcajadasLabel) 
        {
            message.setSmil("5.png");
        } else 
                     if (e.getSource() == coraojosLabel) 
        {
            message.setSmil("6.png");
        } else 
                     if (e.getSource() == besitosLabel) 
        {
            message.setSmil("7.png");
        } else 
                    if (e.getSource() == tapabocaLabel) 
        {
            message.setSmil("8.png");
        } else
                    if (e.getSource() == fiebreLabel) 
        {
            message.setSmil("9.png");
        } else
                     if (e.getSource() == gatoriendoLabel) 
        {
            message.setSmil("10.png");
        } else
                    if (e.getSource() == gatocoraLabel) 
        {
            message.setSmil("11.png");
        } else
                   if (e.getSource() == monoojosLabel) 
        {
            message.setSmil("12.png");
        } else
                  if (e.getSource() == monoorejasLabel) 
        {
            message.setSmil("13.png");
        } else
                 if (e.getSource() == monobocaLabel) 
        {
            message.setSmil("14.png");
        } else
                 if (e.getSource() == abuelaLabel) 
        {
            message.setSmil("15.png");
        } else
                if (e.getSource() == abueloLabel) 
        {
            message.setSmil("16.png");
        } else
               if (e.getSource() == angelLabel) 
        {
            message.setSmil("17.png");
        } else
               if (e.getSource() == pandaLabel) 
        {
            message.setSmil("18.png");
        } else
               if (e.getSource() == okLabel) 
        {
            message.setSmil("19.png");
        } else
               if (e.getSource() == nolikeLabel) 
        {
            message.setSmil("20.png");
        } else
              if (e.getSource() == likeLabel) 
        {
            message.setSmil("21.png");
        } else
              if (e.getSource() == bicepLabel) 
        {
            message.setSmil("22.png");
        } else
                  if (e.getSource() == cruzLabel) 
        {
            message.setSmil("23.png");
        }
                  
        try 
        {
            chat.sendMessage(message);
        } 
        catch (RemoteException ex) 
        {
            Logger.getLogger(VerChat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    @Override
    public void mousePressed(MouseEvent e) 
    {
        
    }

    @Override
    public void mouseReleased(MouseEvent e) 
    {
        
    }

    @Override
    public void mouseEntered(MouseEvent e) 
    {
        
    }

    @Override
    public void mouseExited(MouseEvent e) 
    {
        
    }

    private void addListeners() 
    {
         LentesLabel.addMouseListener(this);
         dudaLabel.addMouseListener(this);
         desacuerdoLabel.addMouseListener(this);
         llorandoLabel.addMouseListener(this);
         provacandoLabel.addMouseListener(this);
         carcajadasLabel.addMouseListener(this);
         coraojosLabel.addMouseListener(this);
         besitosLabel.addMouseListener(this);
         tapabocaLabel.addMouseListener(this);
         fiebreLabel.addMouseListener(this);
         gatoriendoLabel.addMouseListener(this);
         gatocoraLabel.addMouseListener(this);
         monoojosLabel.addMouseListener(this);
         monoorejasLabel.addMouseListener(this);
         monobocaLabel.addMouseListener(this);
         abuelaLabel.addMouseListener(this);
         abueloLabel.addMouseListener(this);
         angelLabel.addMouseListener(this);
         pandaLabel.addMouseListener(this);
         okLabel.addMouseListener(this);
         nolikeLabel.addMouseListener(this);
         likeLabel.addMouseListener(this);
         bicepLabel.addMouseListener(this);
         cruzLabel.addMouseListener(this);
         chatInputText.addKeyListener(this);
    }

    @Override
    public void keyTyped(KeyEvent e) 
    {
        
    }

    @Override
    public void keyPressed(KeyEvent e) 
    {
        if (e.getKeyCode() == KeyEvent.VK_ENTER) 
        {
            sendNewMessage();
        }
    }

    @Override
    public void keyReleased(KeyEvent e) 
    {
        
    }

    private void sendNewMessage() 
    {
        String inputMessage = chatInputText.getText();
        chatInputText.setText("");
        Mensaje message = new Mensaje();
        message.setUsuario(username);
        message.setMsg(inputMessage);
        message.setTipo("client");
        message.setDatos(new Date());
        try 
        {
            chat.sendMessage(message);
        } 
        catch (RemoteException ex) 
        {
            Logger.getLogger(VerChat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
